# Generated by Django 4.2.7 on 2023-11-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tittle',
            new_name='title',
        ),
    ]
