# Generated by Django 4.2.7 on 2023-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_tittle_collection_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
    ]
