# Generated by Django 4.2.7 on 2023-12-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_id_alter_cartiteam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartiteam',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
    ]
